language: go
go:
  - 1.12.x

before_install:
  - go get -t -v ./...

script:
  - cd identity && go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
